// Generated by hand from RecruitSphereAI.Core (Entities, Dtos, Enums).
// Guid -> string, DateTimeOffset/DateTime -> string (ISO 8601), decimal -> number.
// See src/types/enums.ts for how JobStatus/ApplicationStatus/InterviewStatus numbers map to labels.

export interface UserDto {
  id: string;
  email: string;
  fullName: string;
  role: string; // "Candidate" | "Recruiter" | "HiringManager" | "Admin"
}

export interface AuthResponse {
  success: boolean;
  message: string;
  accessToken?: string | null;
  refreshToken?: string | null;
  user?: UserDto | null;
}

export interface RegisterRequest {
  email: string;
  fullName: string;
  password: string;
  confirmPassword: string;
  role: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

// --- Organization / people -------------------------------------------------

export interface Organization {
  id: string;
  name: string;
  description?: string | null;
  industry?: string | null;
  website?: string | null;
  createdAt: string;
}

export interface Department {
  id: string;
  organizationId: string;
  name: string;
  description?: string | null;
}

export interface Recruiter {
  id: string;
  userId: string;
  organizationId: string;
  organization?: Organization | null;
  positionTitle?: string | null;
}

export interface Candidate {
  id: string;
  userId: string;
  bio?: string | null;
  experienceYears: number;
  education?: string | null;
  skills?: string | null;
  resumeUrl?: string | null;
}

// --- Jobs --------------------------------------------------------------

export interface JobPosting {
  id: string;
  title: string;
  description: string;
  requirements?: string | null;
  location?: string | null;
  salary?: number | null;
  status: number; // JobStatus enum ordinal — see types/enums.ts
  recruiterId: string;
  recruiter?: Recruiter | null;
  departmentId?: string | null;
  department?: Department | null;
  organizationId?: string | null;
  organization?: Organization | null;
  createdAt: string;
}

export interface CreateJobRequest {
  title: string;
  description: string;
  requirements?: string;
  location?: string;
  salary?: number;
  departmentId?: string;
  organizationId?: string;
}

export interface UpdateJobRequest {
  title: string;
  description: string;
  requirements?: string;
  location?: string;
  salary?: number;
}

export interface UpdateJobStatusRequest {
  status: string; // "Draft" | "Published" | "Closed" | "Archived"
}

// --- Applications --------------------------------------------------------

export interface Application {
  id: string;
  jobPostingId: string;
  jobPosting?: JobPosting | null;
  candidateId: string;
  candidate?: Candidate | null;
  status: number; // ApplicationStatus enum ordinal
  appliedDate: string;
}

export interface SubmitApplicationRequest {
  jobPostingId: string;
}

export interface UpdateApplicationStatusRequest {
  status: string; // "Submitted" | "UnderReview" | "Interviewing" | "Accepted" | "Rejected"
}

// --- Interviews ------------------------------------------------------------

export interface Interview {
  id: string;
  applicationId: string;
  application?: Application | null;
  scheduledDate: string;
  status: number; // InterviewStatus enum ordinal
  meetingLink?: string | null;
}

export interface ScheduleInterviewRequest {
  applicationId: string;
  scheduledDate: string; // ISO string
  mode: string; // meeting link / mode text
}

export interface UpdateInterviewStatusRequest {
  status: string; // "Scheduled" | "Completed" | "Cancelled" | "NoShow"
}

// --- AI ----------------------------------------------------------------

export interface ParseResumeRequest {
  resumeText: string;
}
export interface ParseResumeResponse {
  parsedResult: string;
}

export interface CalculateMatchScoreRequest {
  candidateProfile: string;
  jobDescription: string;
}
export interface CalculateMatchScoreResponse {
  matchScore: number;
}

export interface ExtractSkillsRequest {
  text: string;
}
export interface ExtractSkillsResponse {
  skills: string[];
}

export interface GenerateJobRecommendationRequest {
  candidateSkills: string;
}
export interface GenerateJobRecommendationResponse {
  recommendation: string;
}

// --- Misc --------------------------------------------------------------

export interface ApiErrorShape {
  message?: string;
  title?: string;
  errors?: Record<string, string[]>;
}

// --- Feedback ------------------------------------------------------------

export interface Feedback {
  id: string;
  applicationId: string;
  candidateId: string;
  userId?: string | null;
  user?: UserDto | null;
  comments: string;
  rating?: number | null;
  createdAt: string;
}

export interface SubmitFeedbackRequest {
  applicationId: string;
  comments: string;
  rating?: number;
}

// --- Admin ---------------------------------------------------------------

export interface AdminAnalyticsResponse {
  totalUsers: number;
  totalCandidates: number;
  totalRecruiters: number;
  totalHiringManagers: number;
  totalAdmins: number;
  totalJobPostings: number;
  jobsByStatus: Record<string, number>;
  totalApplications: number;
  applicationsByStatus: Record<string, number>;
  totalInterviews: number;
  interviewsByStatus: Record<string, number>;
  averageDisclosedSalary?: number | null;
  totalOrganizations: number;
}
